name: Arm Image Build Test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  NODE_VERSION: 16.19.1
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: musicminion/e5
  IMAGE_TAG: arm

jobs:
      build-push-image:
        runs-on: macos-latest-xlarge

        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
          - name: Build and push Docker image
            id: docker_build
            uses: docker/build-push-action@v2
            with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                platforms: linux/arm64
