name: auto-deploy
on:
  workflow_run:
    workflows: [auto-build]
    branches: [master, dev]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # 需要保证HOST_E5_Folder是你的文件夹，里面已经配置好的相关的环境变量
        # 例如：HOST_E5_FOLDER=/home/xxx/e5
        script: |
          cd ${{ secrets.HOST_E5_FOLDER }}
          docker-compose down
          docker-compose pull
          docker-compose up -d
          exit
